hdfs:
  user: cloudera
  fsUri: hdfs://quickstart.cloudera:8020/
  file:
    maxNumber: 5
    maxSizeMb: 128
  path:
    landing: /user/cloudera/applications/@application.name@/landing/
    permissions: -rwxr-xr-x

impala:
  url: jdbc:impala://quickstart.cloudera:21050
  driver: com.cloudera.impala.jdbc.Driver
  db: @impala.db.name@
  table:
    ingestionLog: @impala.log.tableName@
