hdfs:
  user: cloudera
  fsUri: hdfs://quickstart.cloudera:8020/user/cloudera
  path:
    landing: /user/cloudera/applications/@application.name@/landing/
    maxFiles: 3
    permissions: -rwxr-xr-x

impala:
  url: jdbc:impala://quickstart.cloudera:21050
  driver: com.cloudera.impala.jdbc.Driver
  db: @impala.dbName@
  table:
    ingestionLog: @impala.log.tableName@
