appName: @appName@
hdfs:
  user: cloudera
  defaultNode: quickstart.cloudera
  fsUri: hdfs://${hdfs.defaultNode}:8020/user/${hdfs.user}
  path:
    landing: /user/${hdfs.user}/applications/${appName}/landing/
    permissions: -rwxr-xr-x

impala:
  url: jdbc:impala://${hdfs.defaultNode}:21050
  driver: com.cloudera.impala.jdbc.Driver
  db: @appName@
  table:
    ingestionLog: t_ingestion_log
