appName: lake_cedacri
hdfs:
  user: cloudera
  defaultNode: quickstart.cloudera
  fsUri: hdfs://${hdfs.defaultNode}:8020/user/${hdfs.user}
  path:
    landingRoot: /user/${hdfs.user}/applications/${appName}/landing/
    schemasRoot: /user/${hdfs.user}/applications/${appName}/schema/
    permissions: -rwxr-xr-x

jdbc:
  hive:
    url: jdbc:hive2://${hdfs.defaultNode}:10000/${appName}
    driver: org.apache.hive.jdbc.HiveDriver
  impala:
    url: jdbc:impala://${hdfs.defaultNode}:21050/${appName}
    driver: com.cloudera.impala.jdbc.Driver
  table:
    prefix: t_rw_ingested_